
title: Hanif Zaman's Homepage
page-top-title: Hanif Zaman
top-section-bg-text: Exploring Biochemistry
home-subtitle: Welcome to My Portfolio!
#copyright-text: '&copy; Sen Li 2023. All Rights Reserved.'
